version: '3'

services:
  api:
    container_name: "jibberjabber-post"
    image: "jibberjabber:latest"
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      DB_USER: fabrizioserial
      DB_PASSWORD: welcome12
      DB_NAME: JibberJabber
      DB_HOST: postgres
      DB_PORT: 5432

  postgres:
    container_name: postgres_db
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: fabrizioserial
      POSTGRES_PASSWORD: welcome12
      POSTGRES_DB: JibberJabber
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    external: true